name: C/C++ CI

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./autogen.sh && ./checonfigure --enable-dns && make check && make 
